title: Large scale data processing @ Datascience WRUST
logo: /assets/img/logo.png
description: Large scale data processing course page
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
